//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLpractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int id { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> id_from { get; set; }
        public Nullable<int> id_to { get; set; }
        public string mess { get; set; }
        public Nullable<System.DateTime> date_sent { get; set; }
    }
}
